services:
  laravel:
    build: .
    container_name: laravel
    environment:
      PHP_OPCACHE_ENABLE: 1
      PRODUCTION: 0
    ports:
      - 8080:80
    volumes:
      - vendor-data:/opt/laravel/vendor
      - storage-data:/opt/laravel/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://laravel/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}", "-d", "${DB_DATABASE}"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  db_data:
  vendor-data:
  storage-data:
